const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealElements=[...document.querySelectorAll('.reveal')];
if('IntersectionObserver'in window&&!reducedMotion){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.1});revealElements.forEach(element=>revealObserver.observe(element))}else{revealElements.forEach(element=>element.classList.add('visible'))}

const bar=document.getElementById('bar');
function updateProgress(){const root=document.documentElement;const max=root.scrollHeight-innerHeight;const value=max>0?scrollY/max*100:0;if(bar)bar.style.height=`${value}%`}
addEventListener('scroll',updateProgress,{passive:true});updateProgress();

const links=[...document.querySelectorAll('.top nav a')];
const sections=[...document.querySelectorAll('main section[id]')];
if('IntersectionObserver'in window){const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(link=>link.removeAttribute('aria-current'));const current=links.find(link=>link.getAttribute('href')===`#${entry.target.id}`);if(current)current.setAttribute('aria-current','true')}}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(section=>navObserver.observe(section))}

const workflowData={
  nx:{eyebrow:'SIEMENS NX / CAPTURED WORKSPACE',title:'From interface requirements to editable geometry.',intro:'One verified NX capture is presented as three focused views: the complete workspace, Assembly Navigator and the modeled assembly. The sequence below explains how the CAD work progresses.',image:'assets/nx.webp',views:[['contain','Full NX workspace'],['zoom-left','Assembly Navigator'],['zoom-center','3D assembly focus']],steps:[['01','Define interfaces','Envelope, mounting points, clearances and service access.'],['02','Build or import','Create parts or handle STEP, Parasolid and NX geometry.'],['03','Assemble','Place components and apply relationships or constraints.'],['04','Inspect','Review fit, packaging and accessible interfaces.'],['05','Revise','Update geometry when field or analysis findings change.'],['06','Handoff','Keep model structure usable for CAE and documentation.']]},
  ansys:{eyebrow:'ANSYS MECHANICAL / CAPTURED WORKSPACE',title:'Turn the CAD model into an engineering question.',intro:'The verified Mechanical capture is separated into full-workspace, model-tree and contour-result views. They show the same session; the process makes the assumptions and interpretation explicit.',image:'assets/ansys.webp',views:[['contain','Full Mechanical workspace'],['zoom-left','Outline and setup'],['zoom-center','Result contour focus']],steps:[['01','Define question','Choose the risk or response that needs evaluation.'],['02','Prepare model','Simplify geometry and define relevant contacts.'],['03','Assign inputs','Material, supports, loads or thermal conditions.'],['04','Mesh','Use a mesh appropriate to geometry and purpose.'],['05','Solve and inspect','Read stress, deformation or temperature fields.'],['06','Iterate','Revise assumptions or geometry and check again.']]}
};
const dialog=document.getElementById('workflow-dialog');const dialogContent=document.getElementById('dialog-content');
function openWorkflow(key){const data=workflowData[key];if(!data||!dialog||!dialogContent)return;dialogContent.innerHTML=`<div class="dialog-inner"><header class="dialog-head"><p class="eyebrow">${data.eyebrow}</p><h2 id="dialog-title">${data.title}</h2><p>${data.intro}</p></header><div class="focus-gallery">${data.views.map(([className,label])=>`<figure class="focus-shot ${className}"><img src="${data.image}" alt="${label}"><label>${label}</label></figure>`).join('')}</div><div class="process-list">${data.steps.map(([number,title,text])=>`<article><span>${number}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></div>`;dialog.showModal();document.body.style.overflow='hidden';playTone(520,.045)}
document.querySelectorAll('[data-workflow]').forEach(button=>button.addEventListener('click',()=>openWorkflow(button.dataset.workflow)));
document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());
dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
dialog?.addEventListener('close',()=>{document.body.style.overflow=''});

let audioContext=null;let soundEnabled=false;const soundToggle=document.getElementById('sound-toggle');
function playTone(frequency=440,duration=.035){if(!soundEnabled)return;audioContext??=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator();const gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.055,audioContext.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration+.01)}
soundToggle?.addEventListener('click',()=>{soundEnabled=!soundEnabled;soundToggle.setAttribute('aria-pressed',String(soundEnabled));soundToggle.textContent=soundEnabled?'Sound on':'Sound off';if(soundEnabled){audioContext??=new(window.AudioContext||window.webkitAudioContext)();playTone(660,.08)}});
document.querySelectorAll('a.btn,.cv').forEach(control=>control.addEventListener('click',()=>playTone(460,.03)));

if(!reducedMotion&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;card.style.setProperty('--ry',`${x*3.4}deg`);card.style.setProperty('--rx',`${y*-3.4}deg`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--ry','0deg');card.style.setProperty('--rx','0deg')})})}
